# ---*** R10 CODES ***--- N°7

library(tidyverse)
library(openxlsx)
library(rvest)

enlaces <- c(
  "https://www.cepchile.cl/investigacion/desentranando-el-7-de-mayo-un-analisis-de-la-eleccion-del-consejo-constitucional/", 
  "https://www.cepchile.cl/investigacion/una-constitucion-que-cierre-brechas-entre-mujeres-y-hombres-elementos-para-la-discusion/", 
  "https://www.cepchile.cl/investigacion/altruismo-cooperacion-entre-adolescentes-chilenos-analisis-de-su-conducta-prosocial/", 
  "https://www.cepchile.cl/investigacion/falta-de-conciliacion-entre-trabajo-y-familia-desafio-para-avanzar-en-mayor-insercion-laboral-femenina/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-abril-2023/", 
  "https://www.cepchile.cl/investigacion/promoviendo-la-competencia-en-el-mercado-de-seguros-de-salud-en-chile-una-mirada-desde-la-economia-del-comportamiento/", 
  "https://www.cepchile.cl/investigacion/homenaje-a-roberto-torretti/", 
  "https://www.cepchile.cl/investigacion/distribucion-de-la-cotizacion-adicional-en-la-reforma-de-pensiones/", 
  "https://www.cepchile.cl/investigacion/el-administrador-previsional-autonomo-de-la-reforma-de-pensiones-nudos-criticos-y-recomendaciones/", 
  "https://www.cepchile.cl/investigacion/seminario-experiencia-comparada-sobre-derechos-sociales/", 
  "https://www.cepchile.cl/investigacion/bases-institucionales-del-proceso-constituyente-un-analisis-de-la-tradicion-constitucional-chilena/", 
  "https://www.cepchile.cl/investigacion/futuros-presentes-nuevas-opciones-riesgos-en-escenarios-complejos/", 
  "https://www.cepchile.cl/investigacion/efectos-pandemia-en-bienestar-socioemocional-ninos-adolescentes-chile-y-mundo/", 
  "https://www.cepchile.cl/investigacion/constitucion-pre-estallido-michelle-bachelet-cuanto-rinde-hoy/", 
  "https://www.cepchile.cl/investigacion/libertad-de-expresion-ante-comite-de-etica-convencion-constitucional/", 
  "https://www.cepchile.cl/investigacion/precondiciones-para-la-construccion-de-un-estado-social-en-chile/", 
  "https://www.cepchile.cl/investigacion/apruebo-rechazo-septiembre-2023-expectativas-decepciones-horizontes-para-el-nuevo-proceso-constitucional/", 
  "https://www.cepchile.cl/investigacion/propuestas-para-fomentar-participacion-laboral-femenina-chile/", 
  "https://www.cepchile.cl/investigacion/crisis-educacional-escolar-pospandemia/", 
  "https://www.cepchile.cl/investigacion/momento-economico-internacional-nacional-enero-2023/", 
  "https://www.cepchile.cl/investigacion/estado-regional-analisis-critico-perspectiva-distribucion-de-competencias/", 
  "https://www.cepchile.cl/investigacion/mapuche-en-el-sur-identidad-materialidad-expectativa/", 
  "https://www.cepchile.cl/investigacion/cinco-republicas-una-tradicion-una-historia-del-constitucionalismo-en-chile-1810-2020/", 
  "https://www.cepchile.cl/investigacion/polarizacion-y-fragmentacion-camara-diputados-escenario-del-acuerdo-por-chile/", 
  "https://www.cepchile.cl/investigacion/los-expertos-en-la-convencion-constitucional/", 
  "https://www.cepchile.cl/investigacion/las-side-letters-en-el-contexto-del-cptpp/", 
  "https://www.cepchile.cl/investigacion/pgu-tasas-reemplazo/", 
  "https://www.cepchile.cl/investigacion/sistemas-justicia-consejo-justicia-y-corte-constitucional-cambios-necesitan/", 
  "https://www.cepchile.cl/investigacion/cuan-autonoma-fue-la-convencion-constitucional-lecciones-para-un-posible-nuevo-organo-constituyente/", 
  "https://www.cepchile.cl/investigacion/partido-de-la-gente-la-construccion-del-individualismo-posdemocratico/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2022/", 
  "https://www.cepchile.cl/investigacion/21726-2/", 
  "https://www.cepchile.cl/investigacion/como-elegir-a-los-nuevos-convencionales-tres-alternativas-que-respetan-la-proporcionalidad-representatividad-y-paridad/", 
  "https://www.cepchile.cl/investigacion/edgardo-boeninger-a-sus-97/", 
  "https://www.cepchile.cl/investigacion/varias-naciones-desafios-juridicos/", 
  "https://www.cepchile.cl/investigacion/trabajadores-informales-que-sabemos-de-su-bienestar-social/", 
  "https://www.cepchile.cl/investigacion/parcelaciones-rurales-propuestas-para-el-desarrollo-de-las-subdivisiones-rusticas-en-chile/", 
  "https://www.cepchile.cl/investigacion/proyecto-de-ley-royalty-a-la-mineria/", 
  "https://www.cepchile.cl/investigacion/mejor-igual-o-peor-como-cambiaron-las-percepciones-de-desigualdad-con-el-estallido-social/", 
  "https://www.cepchile.cl/investigacion/propiedad-y-recursos-naturales-un-nuevo-regimen/", 
  "https://www.cepchile.cl/investigacion/la-geografia-del-poder-desafios-juridicos-del-estado-regional/", 
  "https://www.cepchile.cl/investigacion/los-derechos-y-su-tutela-judicial-riesgos-y-oportunidades/", 
  "https://www.cepchile.cl/investigacion/edgardo-boeninger-sobre-la-crisis-de-representatividad-y-la-democracia-en-chile/", 
  "https://www.cepchile.cl/investigacion/desafios-para-la-gestion-del-agua-y-la-propuesta-de-nueva-constitucion/", 
  "https://www.cepchile.cl/investigacion/sistema-politico-mayor-o-menor-gobernabilidad/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-agosto-2022/", 
  "https://www.cepchile.cl/investigacion/estimaciones-del-costo-fiscal-directo-de-la-propuesta-de-nueva-constitucion/", 
  "https://www.cepchile.cl/investigacion/relaciones-internacionales-y-politica-exterior-en-la-propuesta-de-nueva-constitucion/", 
  "https://www.cepchile.cl/investigacion/zona-de-curvas-la-convencion-y-la-camara-en-comparacion/", 
  "https://www.cepchile.cl/investigacion/salario-minimo-en-chile-un-aporte-a-la-discusion/", 
  "https://www.cepchile.cl/investigacion/el-financiamiento-subnacional-un-problema-constituyente/", 
  "https://www.cepchile.cl/investigacion/el-conflicto-ruso-ucraniano-miradas-historicas/", 
  "https://www.cepchile.cl/investigacion/ampliacion-del-sistema-de-donaciones-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-junio-2022/", 
  "https://www.cepchile.cl/investigacion/propuestas-para-la-transicion-constitucional/", 
  "https://www.cepchile.cl/investigacion/como-deberan-fallar-los-tribunales-bajo-la-nueva-constitucion/", 
  "https://www.cepchile.cl/investigacion/los-intelectuales-de-izquierda-y-el-problema-del-triunfo/", 
  "https://www.cepchile.cl/investigacion/midiendo-la-calidad-del-empleo-en-chile-actualizacion-a-febrero-de-2022/", 
  "https://www.cepchile.cl/investigacion/partidos-politicos-en-la-propuesta-de-nueva-constitucion-una-oportunidad-perdida/", 
  "https://www.cepchile.cl/investigacion/desafios-para-la-democracia-el-populismo-como-una-nueva-forma-de-gobierno/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-abril-2022/", 
  "https://www.cepchile.cl/investigacion/analisis-y-propuestas-sobre-la-reconversion-de-areas-industriales-urbanas-en-chile/", 
  "https://www.cepchile.cl/investigacion/abandonar-la-modernidad-discurso-y-praxis-decolonial-en-la-convencion-constitucional-chilena/", 
  "https://www.cepchile.cl/investigacion/el-problema-de-la-defensa-de-la-constitucion/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2022/", 
  "https://www.cepchile.cl/investigacion/tiempos-de-traslado-y-jornada-laboral-analisis-para-el-gran-valparaiso/", 
  "https://www.cepchile.cl/investigacion/nueva-educacion-publica-deficiencias-y-desafios-2/", 
  "https://www.cepchile.cl/investigacion/paridad-de-genero-y-financiamiento-electoral/", 
  "https://www.cepchile.cl/investigacion/aumento-en-carga-tributaria-y-crecimiento-evidencia-de-paises-ocde/", 
  "https://www.cepchile.cl/investigacion/la-maquina-del-tiempo/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2021/", 
  "https://www.cepchile.cl/investigacion/competencia-en-el-mercado-laboral-chileno-y-su-efecto-en-la-brecha-salarial-de-genero/", 
  "https://www.cepchile.cl/investigacion/la-gestion-hidrica-en-australia-e-israel-dos-modelos-un-solo-fin/", 
  "https://www.cepchile.cl/investigacion/dos-factores-claves-para-considerar-en-una-reforma-de-pensiones/", 
  "https://www.cepchile.cl/investigacion/sesgo-socioeconomico-en-las-notas-de-ensenanza-media/", 
  "https://www.cepchile.cl/investigacion/notas-sobre-el-parlamentarismo-anglosajon-los-casos-de-inglaterra-y-las-trece-colonias-siglos-xvii-y-xviii/", 
  "https://www.cepchile.cl/investigacion/cuidados-de-largo-plazo-lecciones-de-la-evidencia-comparada/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-agosto-2021/", 
  "https://www.cepchile.cl/investigacion/comunidades-semanticas-y-distinciones-politicas-en-el-discurso-de-los-convencionales-constituyentes/", 
  "https://www.cepchile.cl/investigacion/elecciones-a-la-convencion-constituyente-innovacion-y-renovacion/", 
  "https://www.cepchile.cl/investigacion/chile-postsecular-la-necesidad-de-una-exploracion-comparada/", 
  "https://www.cepchile.cl/investigacion/semanticas-constitucionales-un-analisis-de-los-programas-de-los-convencionales-constituyentes/", 
  "https://www.cepchile.cl/investigacion/ciclo-la-izquierda-chilena-miradas-desde-el-presente-iii/", 
  "https://www.cepchile.cl/investigacion/ciclo-las-derechas-chilenas-miradas-desde-el-presente-iii/", 
  "https://www.cepchile.cl/investigacion/ciclo-la-izquierda-chilena-miradas-desde-el-presente-ii/", 
  "https://www.cepchile.cl/investigacion/trayectorias-y-dinamicas-en-los-delitos-que-ha-pasado-durante-la-pandemia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-junio-2021/", 
  "https://www.cepchile.cl/investigacion/entrando-en-los-detalles-de-la-convencion-constitucional-secretaria-tecnica-y-comite-externo-de-asignaciones/", 
  "https://www.cepchile.cl/investigacion/ciclo-las-derechas-chilenas-miradas-desde-el-presente-ii/", 
  "https://www.cepchile.cl/investigacion/ciclo-la-izquierda-chilena-miradas-desde-el-presente-i/", 
  "https://www.cepchile.cl/investigacion/royalties-mineros-que-dice-la-evidencia-comparada/", 
  "https://www.cepchile.cl/investigacion/tres-decadas-de-evolucion-macroeconomica-de-las-regiones-en-chile/", 
  "https://www.cepchile.cl/investigacion/ciclo-las-derechas-chilenas-miradas-desde-el-presente-i/", 
  "https://www.cepchile.cl/investigacion/historia-y-evolucion-del-financiamiento-a-los-gobiernos-regionales/", 
  "https://www.cepchile.cl/investigacion/entre-libertad-y-hegemonia-analisis-semantico-de-constituciones-en-america-latina-europa-y-estados-unidos/", 
  "https://www.cepchile.cl/investigacion/propuestas-de-reglamento-para-la-convencion-constitucional-encuentros-y-desencuentros/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-abril-2021/", 
  "https://www.cepchile.cl/investigacion/personas-dependientes-quienes-son-quienes-los-cuidan-y-cual-es-el-costo-de-la-asistencia/", 
  "https://www.cepchile.cl/investigacion/la-utilizacion-de-redes-sociales-en-campanas-politicas-problemas-y-posibles-soluciones/", 
  "https://www.cepchile.cl/investigacion/la-investigacion-en-ciencias-sociales-y-humanidades-sus-debates-e-impactos/", 
  "https://www.cepchile.cl/investigacion/megasequia-diagnostico-impactos-y-propuestas/", 
  "https://www.cepchile.cl/investigacion/el-costo-del-estallido-social-en-el-ingreso-a-la-educacion-superior/", 
  "https://www.cepchile.cl/investigacion/ira-y-tiempo-sloterdijk-y-el-momento-constitucional/", 
  "https://www.cepchile.cl/investigacion/sistemas-de-pensiones-en-el-mundo-lecciones-para-chile/", 
  "https://www.cepchile.cl/investigacion/la-paradoja-del-crecimiento-economico-y-las-pensiones-decepcion-y-esperanza/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2020/", 
  "https://www.cepchile.cl/investigacion/conviviendo-con-el-covid-19/", 
  "https://www.cepchile.cl/investigacion/donaciones-en-chile-analisis-del-marco-legal-vigente-y-propuestas-para-su-modernizacion/", 
  "https://www.cepchile.cl/investigacion/otro-costo-de-la-pandemia-la-perdida-salarial-por-el-despido/", 
  "https://www.cepchile.cl/investigacion/la-constitucion-del-disenso/", 
  "https://www.cepchile.cl/investigacion/estructura-de-asambleas-constituyentes-en-america-latina-que-se-puede-aprender/", 
  "https://www.cepchile.cl/investigacion/impuestos-corporativos-e-inversion-privada-una-actualizacion-de-la-evidencia/", 
  "https://www.cepchile.cl/investigacion/plebiscito-en-tiempos-de-pandemia-que-medidas-son-necesarias-para-realizar-un-plebiscito-nacional-seguro/", 
  "https://www.cepchile.cl/investigacion/midiendo-la-calidad-del-empleo-en-chile-actualizacion-a-junio-de-2020/", 
  "https://www.cepchile.cl/investigacion/concordancias-del-mundo-en-andres-bello/", 
  "https://www.cepchile.cl/investigacion/una-mirada-al-sistema-de-pensiones-chileno-antecedentes-y-propuestas-para-el-futuro/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-agosto-2020/", 
  "https://www.cepchile.cl/investigacion/el-reglamento-de-la-convencion-y-el-riesgo-de-la-hoja-en-blanco/", 
  "https://www.cepchile.cl/investigacion/productividad-y-concentracion-experiencia-por-sectores-en-el-caso-de-chile/", 
  "https://www.cepchile.cl/investigacion/el-rol-de-los-test-en-la-pandemia-definiciones-y-recomendaciones/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-junio-2020/", 
  "https://www.cepchile.cl/investigacion/el-primer-constitucionalismo-chileno-reflexiones-historicas-para-la-discusion-actual/", 
  "https://www.cepchile.cl/investigacion/el-momento-politico-mayo-2020-crisis-social-y-pandemia/", 
  "https://www.cepchile.cl/investigacion/politica-y-sostenibilidad-fiscal-en-tiempos-de-covid-19-el-caso-de-chile/", 
  "https://www.cepchile.cl/investigacion/la-mejor-futurologia-depende-del-futuro-consideraciones-sociologicas-sobre-la-pandemia/", 
  "https://www.cepchile.cl/investigacion/el-financiamiento-de-los-municipios-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-la-pandemia-y-la-economia-abril-2020/", 
  "https://www.cepchile.cl/investigacion/coronavirus-antecedentes-sanitarios-y-economicos-para-la-discusion/", 
  "https://www.cepchile.cl/investigacion/trayectoria-de-fallecimientos-de-covid-19/", 
  "https://www.cepchile.cl/investigacion/reflexiones-sobre-la-experiencia-de-nueva-zelandia-en-materia-de-desarrollo-politico-economico-y-social/", 
  "https://www.cepchile.cl/investigacion/mirando-el-futuro-acuerdo-constitucional-y-acuerdos-economico-sociales/", 
  "https://www.cepchile.cl/investigacion/dinamica-inmobiliaria-demografia-e-inmigracion-evolucion-reciente-en-santiago/", 
  "https://www.cepchile.cl/investigacion/evolucion-de-la-segregacion-de-los-inmigrantes-en-santiago/", 
  "https://www.cepchile.cl/investigacion/carga-tributaria-en-chile-evidencia-actualizada/", 
  "https://www.cepchile.cl/investigacion/el-desafio-constitucional-algunas-consideraciones/", 
  "https://www.cepchile.cl/investigacion/algunas-reflexiones-sobre-la-propuesta-de-impuesto-a-la-riqueza/", 
  "https://www.cepchile.cl/investigacion/notas-sobre-proyecto-de-ley-de-integracion-social-y-urbana/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2019/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2019/", 
  "https://www.cepchile.cl/investigacion/diferencias-entre-los-datos-de-empleo-del-ine-y-los-de-la-superintendencia-de-pensiones-estamos-frente-a-una-anomalia/", 
  "https://www.cepchile.cl/investigacion/un-aporte-a-la-discusion-del-crecimiento-de-largo-plazo-en-chile/", 
  "https://www.cepchile.cl/investigacion/precios-de-vivienda-quien-tiene-la-razon/", 
  "https://www.cepchile.cl/investigacion/vivienda-social-en-el-barrio-temores-pasajeros-e-infundados/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-agosto-2019/", 
  "https://www.cepchile.cl/investigacion/regulando-los-medicamentos-precaucion-ante-posibles-efectos-adversos/", 
  "https://www.cepchile.cl/investigacion/que-explica-las-diferencias-socioeconomicas-en-las-preferencias-escolares/", 
  "https://www.cepchile.cl/investigacion/el-ciclo-politico-y-los-nuevos-miedos-de-los-chilenos/", 
  "https://www.cepchile.cl/investigacion/adam-smith-el-economista-moral/", 
  "https://www.cepchile.cl/investigacion/hacia-un-esquema-integrado-en-salud-comentarios-a-la-reforma/", 
  "https://www.cepchile.cl/investigacion/te-aconsejo-que-vayas-a-misa-todos-los-domingos-creencia-sin-participacion-en-el-chile-contemporaneo/", 
  "https://www.cepchile.cl/investigacion/caracterizacion-del-desempleo-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-junio-2019/", 
  "https://www.cepchile.cl/investigacion/bienes-de-la-historia/", 
  "https://www.cepchile.cl/investigacion/creo-lo-que-veo-o-veo-lo-que-creo-el-caso-de-las-percepciones-de-corrupcion-en-chile-y-rusia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-abril-2019/", 
  "https://www.cepchile.cl/investigacion/dos-politicas-un-camino-sobre-la-relacion-entre-la-flexibilidad-y-la-satisfaccion-laboral-cuando-la-jornada-es-larga/", 
  "https://www.cepchile.cl/investigacion/existe-sesgo-socioeconomico-en-las-preferencias-de-colegios/", 
  "https://www.cepchile.cl/investigacion/gasto-de-bolsillo-en-salud-una-mirada-al-gasto-en-medicamentos/", 
  "https://www.cepchile.cl/investigacion/el-nombramiento-de-ministros-a-la-corte-suprema-caracterizacion-de-una-practica-1990-2019/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2019/", 
  "https://www.cepchile.cl/investigacion/es-casi-una-experiencia-religiosa-los-desafiliados-religiosos-en-chile/", 
  "https://www.cepchile.cl/investigacion/cargando-con-la-mochila-ajena-resultados-y-desafios-del-nuevo-sistema-de-admision-escolar/", 
  "https://www.cepchile.cl/investigacion/juventud-y-politica-a-30-anos-del-plebiscito/", 
  "https://www.cepchile.cl/investigacion/ni-la-tele-ni-la-radio-ni-manana-en-los-diarios-consumo-de-informacion-politica-en-chile/", 
  "https://www.cepchile.cl/investigacion/en-esta-mesa-no-se-habla-de-politica-redes-de-discusion-politica-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2018/", 
  "https://www.cepchile.cl/investigacion/viviendas-sociales-por-que-no-en-mi-patio-trasero/", 
  "https://www.cepchile.cl/investigacion/caracterizacion-del-mercado-laboral-para-el-adulto-mayor/", 
  "https://www.cepchile.cl/investigacion/radiografia-del-gasto-de-bolsillo-en-salud-en-chile-analisis-del-cambio-en-el-gasto-entre-2012-y-2016/", 
  "https://www.cepchile.cl/investigacion/brecha-salarial-de-genero-evolucion-en-el-periodo-1990-2017/", 
  "https://www.cepchile.cl/investigacion/maternidad-y-desigualdad-no-hay-mejor-anticonceptivo-que-un-futuro-brillante/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-agosto-2018/", 
  "https://www.cepchile.cl/investigacion/existe-sesgo-de-genero-a-la-hora-de-elegir-colegios-estudio-en-base-a-preferencias-reveladas-del-sistema-de-admision-centralizado/", 
  "https://www.cepchile.cl/investigacion/aumentar-la-densidad-de-cotizaciones-clave-en-una-reforma-efectiva-de-pensiones/", 
  "https://www.cepchile.cl/investigacion/el-rol-de-la-filosofia-en-el-desarrollo-del-pensamiento-critico/", 
  "https://www.cepchile.cl/investigacion/encuesta-de-presupuestos-familiares-y-gasto-en-salud-una-primera-mirada/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-junio-2018/", 
  "https://www.cepchile.cl/investigacion/contribuciones-para-una-reforma-a-los-seguros-de-salud-una-propuesta-y-tres-comentarios/", 
  "https://www.cepchile.cl/investigacion/evaluacion-de-los-sistemas-tributarios-rol-de-la-integracion/", 
  "https://www.cepchile.cl/investigacion/por-que-modernizar-el-estado/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-abril-2018/", 
  "https://www.cepchile.cl/investigacion/radiografia-del-gasto-de-bolsillo-en-salud-en-chile-una-mirada-desagregada/", 
  "https://www.cepchile.cl/investigacion/movilidad-urbana-equidad-de-genero-y-participacion-laboral/", 
  "https://www.cepchile.cl/investigacion/reparando-la-reforma-tributaria-un-goodwill-tributario-eficiente/", 
  "https://www.cepchile.cl/investigacion/breves-reflexiones-sobre-la-eleccion-presidencial-de-2017/", 
  "https://www.cepchile.cl/investigacion/movilidad-urbana-santiago-no-es-chile/", 
  "https://www.cepchile.cl/investigacion/malestar-en-chile-a-la-luz-de-las-elecciones-2017/", 
  "https://www.cepchile.cl/investigacion/la-constitucion-y-los-derechos-sociales-el-limite-de-la-democracia/", 
  "https://www.cepchile.cl/investigacion/las-elecciones-2017-en-frio-el-dia-despues/", 
  "https://www.cepchile.cl/investigacion/por-que-cayo-el-crecimiento-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2017/", 
  "https://www.cepchile.cl/investigacion/elecciones-parlamentarias-y-presidenciales-en-frio-criterios-para-dimensionar-los-resultados-de-las-elecciones-2017/", 
  "https://www.cepchile.cl/investigacion/proteccion-a-la-primera-infancia/", 
  "https://www.cepchile.cl/investigacion/un-modelo-de-votante-probable-para-la-encuesta-cep/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2017/", 
  "https://www.cepchile.cl/investigacion/ideas-para-una-politica-social-mas-equitativa-menos-pobreza-en-los-menores/", 
  "https://www.cepchile.cl/investigacion/algunos-problemas-del-nuevo-sistema-proporcional-para-elecciones-parlamentarias/", 
  "https://www.cepchile.cl/investigacion/el-nasciturus-como-persona-lectura-incompleta-doctrina-distorsionada/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2017/", 
  "https://www.cepchile.cl/investigacion/reforma-curricular-para-el-siglo-xxi/", 
  "https://www.cepchile.cl/investigacion/desviaciones-de-la-paridad-cubierta-de-tasas-de-interes/", 
  "https://www.cepchile.cl/investigacion/limitaciones-al-acceso-de-las-garantias-explicitas-en-salud-ges/", 
  "https://www.cepchile.cl/investigacion/evolucion-del-empleo-en-chile-asalariados-y-cuenta-propia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2017/", 
  "https://www.cepchile.cl/investigacion/un-financiamiento-estudiantil-justo-para-la-educacion-superior/", 
  "https://www.cepchile.cl/investigacion/una-contribucion-a-la-discusion-sobre-la-jornada-laboral/", 
  "https://www.cepchile.cl/investigacion/por-que-cayo-la-desigualdad/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2017/", 
  "https://www.cepchile.cl/investigacion/carga-y-estructura-tributaria-en-chile-comparacion-con-paises-ocde/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2017/", 
  "https://www.cepchile.cl/investigacion/moverse-en-santiago-hoy-que-ha-cambiado-en-los-ultimos-anos/", 
  "https://www.cepchile.cl/investigacion/por-que-liceos-de-excelencia/", 
  "https://www.cepchile.cl/investigacion/enfermeria-de-practica-avanzada-en-la-atencion-primaria-ahora-es-el-momento/", 
  "https://www.cepchile.cl/investigacion/desigualdades-laborales-el-empleo-y-la-calificacion-de-la-mano-de-obra-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2016/", 
  "https://www.cepchile.cl/investigacion/las-elecciones-en-frio-el-dia-despues/", 
  "https://www.cepchile.cl/investigacion/medicion-de-la-pobreza-en-chile-e-introduccion-de-indicadores-de-entorno-y-redes/", 
  "https://www.cepchile.cl/investigacion/el-financiamiento-privado-y-la-participacion-electoral/", 
  "https://www.cepchile.cl/investigacion/elecciones-municipales-en-frio-criterios-para-dimensionar-la-participacion-y-los-resultados-electorales-de-las-elecciones-2016/", 
  "https://www.cepchile.cl/investigacion/existe-una-crisis-institucional-en-el-chile-actual/", 
  "https://www.cepchile.cl/investigacion/cambio-en-el-sistema-electoral-simulaciones-de-las-elecciones-de-diputados/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2016/", 
  "https://www.cepchile.cl/investigacion/urgentes-modificaciones-al-nuevo-sistema-de-admision-escolar/", 
  "https://www.cepchile.cl/investigacion/hacia-donde-vamos-en-salud-como-avanzar-hacia-un-sistema-de-seguros-sociales/", 
  "https://www.cepchile.cl/investigacion/restriccion-vehicular-restringir-tarificar-o-incentivar/", 
  "https://www.cepchile.cl/investigacion/reflexiones-en-torno-a-la-educacion-y-el-mercado/", 
  "https://www.cepchile.cl/investigacion/medicion-de-valor-agregado-de-profesores-avances-desafios-y-aplicaciones/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2016/", 
  "https://www.cepchile.cl/investigacion/criterios-generales-para-una-reforma-de-la-educacion-superior/", 
  "https://www.cepchile.cl/investigacion/tres-factores-claves-para-desmunicipalizar-la-educacion-publica/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2016/", 
  "https://www.cepchile.cl/investigacion/gobernanza-de-la-educacion-superior-bases-para-un-analisis-critico-de-la-reforma-propuesta/", 
  "https://www.cepchile.cl/investigacion/una-alternativa-efectiva-para-fortalecer-la-educacion-publica/", 
  "https://www.cepchile.cl/investigacion/el-nuevo-paciente-desafios-para-el-sistema-de-salud/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2016/", 
  "https://www.cepchile.cl/investigacion/el-anteproyecto-del-plan-de-prevencion-y-descontaminacion-atmosferica-resumen-de-principales-medidas/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2016/", 
  "https://www.cepchile.cl/investigacion/una-nota-sobre-desigualdad-de-ingresos-y-reforma-laboral/", 
  "https://www.cepchile.cl/investigacion/que-hacer-con-los-nimby-una-propuesta-de-politica-y-los-desafios-pendientes/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2015/", 
  "https://www.cepchile.cl/investigacion/aporte-solidario-al-ingreso-del-trabajo-asit-una-mejor-alternativa-contra-la-desigualdad/", 
  "https://www.cepchile.cl/investigacion/mejorando-la-salud-hospitalaria-alternativas-para-el-financiamiento-y-la-gestion-i/", 
  "https://www.cepchile.cl/investigacion/mejorando-la-salud-hospitalaria-alternativas-para-el-financiamiento-y-la-gestion-ii/", 
  "https://www.cepchile.cl/investigacion/mejorando-la-salud-hospitalaria-alternativas-para-el-financiamiento-y-la-gestion-iii/", 
  "https://www.cepchile.cl/investigacion/reflexiones-a-proposito-de-la-perdida-de-confianza-de-la-ciudadania-en-sus-instituciones/", 
  "https://www.cepchile.cl/investigacion/la-importancia-de-recuperar-confianzas/", 
  "https://www.cepchile.cl/investigacion/diagnosticos-alternativos-sobre-la-crisis-de-confianza/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2015/", 
  "https://www.cepchile.cl/investigacion/comentarios-sobre-la-reforma-de-transmision-electrica/", 
  "https://www.cepchile.cl/investigacion/sobre-el-limite-urbano-transparencia-y-mercado-del-suelo/", 
  "https://www.cepchile.cl/investigacion/carcel-para-la-colusion-seis-opiniones/", 
  "https://www.cepchile.cl/investigacion/las-reformas-laborales-tienen-impactos-pero-no-siempre-los-que-se-anticipan/", 
  "https://www.cepchile.cl/investigacion/radiografia-del-uso-del-sistema-de-salud-en-chile-1992-2000-2013/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2015/", 
  "https://www.cepchile.cl/investigacion/gratuidad-en-educacion-superior-como-discusion-y-propuestas-en-torno-al-mecanismo-de-asignacion-de-fondos-para-la-gratuidad/", 
  "https://www.cepchile.cl/investigacion/entorno-y-redes-la-dimension-desconocida-de-casen-2013/", 
  "https://www.cepchile.cl/investigacion/expansion-del-giro-de-enap-respuesta-que-no-contesta-la-pregunta/", 
  "https://www.cepchile.cl/investigacion/financiamiento-de-los-partidos-aterrizando-el-informe-engel/", 
  "https://www.cepchile.cl/investigacion/son-atractivos-los-salariosde-la-nueva-carrera-docente/", 
  "https://www.cepchile.cl/investigacion/son-atractivos-los-salarios-de-la-nueva-carrera-docente/", 
  "https://www.cepchile.cl/investigacion/comentarios-al-informe-de-la-comision-engel/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2015/", 
  "https://www.cepchile.cl/investigacion/productividad-en-chile/", 
  "https://www.cepchile.cl/investigacion/proyecto-de-ley-ricarte-soto-las-definiciones-que-faltan/", 
  "https://www.cepchile.cl/investigacion/chile-lidera-ranking-educacional-en-america-latina-avances-y-desafios-para-chile-de-acuerdo-a-terce/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2015/", 
  "https://www.cepchile.cl/investigacion/la-practica-del-financiamiento-privado-en-las-elecciones-parlamentarias/", 
  "https://www.cepchile.cl/investigacion/ley-de-financiamiento-publico-de-los-partidos-comentarios-y-sugerencias/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2015/", 
  "https://www.cepchile.cl/investigacion/dinero-y-politica-una-mezcla-explosiva/", 
  "https://www.cepchile.cl/investigacion/evolucion-positiva-en-la-distribucion-del-ingreso/", 
  "https://www.cepchile.cl/investigacion/compra-de-colegios-mas-dificil-de-lo-que-se-cree/", 
  "https://www.cepchile.cl/investigacion/propuesta-para-un-buen-sistema-de-postulacion-y-admision-a-establecimientos-educacionales-en-chile/", 
  "https://www.cepchile.cl/investigacion/donde-estan-los-hombres-evidencia-a-partir-del-censo-la-casen-y-la-fps/", 
  "https://www.cepchile.cl/investigacion/seguro-unico-o-multiseguros-analisis-del-informe-de-la-comision-presidencial-de-salud/", 
  "https://www.cepchile.cl/investigacion/cambios-en-la-aprobacion-presidencial/", 
  "https://www.cepchile.cl/investigacion/cierre-de-colegios-amenaza-o-advertencia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2014/", 
  "https://www.cepchile.cl/investigacion/causas-y-consecuencias-del-problema-energetico-en-chile-una-vision-desde-la-macroeconomia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2014/", 
  "https://www.cepchile.cl/investigacion/sobre-el-lucro-en-educacion-escolar/", 
  "https://www.cepchile.cl/investigacion/antecedentes-para-perfeccionar-la-formacion-inicial-docente/", 
  "https://www.cepchile.cl/investigacion/desmunicipalizacion-antecedentes-para-la-nueva-institucionalidad-de-la-educacion-escolar-publica/", 
  "https://www.cepchile.cl/investigacion/efecto-pares-que-sabemos-realmente/", 
  "https://www.cepchile.cl/investigacion/representacion-de-los-pueblos-indigenas-en-el-congreso-preguntas-a-considerar/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2014/", 
  "https://www.cepchile.cl/investigacion/fin-del-financiamiento-compartido-analisis-del-proyecto-de-ley-y-propuestas/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2014/", 
  "https://www.cepchile.cl/investigacion/reflexiones-sobre-el-modelo-crecimiento-desigualdad-y-prosperidad-en-la-economia-global/", 
  "https://www.cepchile.cl/investigacion/perfeccionamiento-del-financiamiento-escolar-y-alternativas-para-terminar-con-el-financiamiento-compartido/", 
  "https://www.cepchile.cl/investigacion/reforma-tributaria-impuestos-verdes-e-implicancias-de-politica-ambiental/", 
  "https://www.cepchile.cl/investigacion/los-desafios-pendientes-del-convenio-169/", 
  "https://www.cepchile.cl/investigacion/sobre-impuestos-desigualdad-y-reforma-tributaria/", 
  "https://www.cepchile.cl/investigacion/mercado-laboral-el-desafio-de-la-capacitacion-conclusiones-del-ciclo-de-politicas-publicas/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2014/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2014/", 
  "https://www.cepchile.cl/investigacion/combatiendo-la-desigualdad-conclusiones-del-ciclo-de-politicas-publicas-panel-de-pobreza-y-desigualdad/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2013/", 
  "https://www.cepchile.cl/investigacion/se-nos-apaga-la-luz-conclusiones-del-ciclo-de-politicas-publicas-panel-de-energia/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2013/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2013/", 
  "https://www.cepchile.cl/investigacion/desigualdad-segregacion-y-resultados-educacionales-evidencia-desde-el-metro-de-santiago/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2013/", 
  "https://www.cepchile.cl/investigacion/julio-philippi-izquierdo-jurista-legislador-negociador-internacional-en-el-centenario-de-su-nacimiento/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2013/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2013/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-noviembre-2012/", 
  "https://www.cepchile.cl/investigacion/pobreza-y-desigualdad-donde-estamos-hacia-donde-vamos/", 
  "https://www.cepchile.cl/investigacion/reforma-tributaria-en-chile-balance-y-perspectivas-futuras-octubre-2012/", 
  "https://www.cepchile.cl/investigacion/reforma-tributaria-en-chile-balance-y-perspectivas-futuras-octubre-2012-2/", 
  "https://www.cepchile.cl/investigacion/como-evaluar-una-politica-de-reconstruccion-una-mirada-multi-dimensional-a-dos-anos-del-terremoto-del-27-de-febrero-de-2010-en-chile/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-septiembre-2012/", 
  "https://www.cepchile.cl/investigacion/lucro-universidad-y-filantropia/", 
  "https://www.cepchile.cl/investigacion/universidad-y-lucro-o-el-dilema-de-la-cobertura/", 
  "https://www.cepchile.cl/investigacion/la-universidad-y-el-lucro-como-impedirlo-y-por-que/", 
  "https://www.cepchile.cl/investigacion/universidad-y-lucro/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-julio-2012/", 
  "https://www.cepchile.cl/investigacion/reforma-tributaria-en-chile-resumen-y-contraste-de-propuestas-junio-2012/", 
  "https://www.cepchile.cl/investigacion/reforma-tributaria-en-chile-resumen-y-contraste-de-propuestas-junio-2012-2/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-mayo-2012/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-marzo-2012/", 
  "https://www.cepchile.cl/investigacion/el-momento-economico-internacional-y-nacional-enero-2012/", 
  "https://www.cepchile.cl/investigacion/fortalecimiento-de-la-educacion-escolar-publica-desmunicipalizacion/" 
)

resultados <- list()

for (i in 1:length(enlaces)) {
  url <- enlaces[i]
  page <- read_html(url)
  
  titulo <- page %>%
    html_node(".banner-title") %>%
    html_text()
  
  fecha_publicacion <- page %>%
    html_node(".banner-date") %>%
    html_text()
  
  autores <- page %>%
    html_node(".lyrics p") %>%
    html_text()
  
  etiquetas <- page %>%
    html_nodes(".display-badges .badge") %>%
    html_text() %>%
    paste(collapse = ", ")
  
  edicion <- page %>%
    html_node(".number-single") %>%
    html_text()
  
  resultados[[i]] <- data.frame(Título = titulo,
                                `Fecha de publicación` = fecha_publicacion,
                                Autor = autores,
                                Etiquetas = etiquetas,
                                Edición = edicion,
                                URL = url)
}

datos_completos <- do.call(rbind, resultados)

print(datos_completos)

write.xlsx(datos_completos, "CEP Puntos de Referencia.xlsx")
