# ---*** R10 CODES ***--- N°54

library(rvest)
library(tidyverse)
library(openxlsx)

enlaces <- c(
  "https://fundacionsol.cl/blog/actualidad-13/post/fuerzas-armadas-y-de-orden-en-defensa-de-sus-pensiones-7374",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajadores-as-del-mundo-unamonos-un-homenaje-a-nuestra-companera-7365",
  "https://fundacionsol.cl/blog/actualidad-13/post/condonacion-del-cae-un-minimo-etico-7340",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuando-la-riqueza-genera-pobreza-el-caso-del-sistema-previsional-chileno-7335",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-millones-del-gran-empresariado-para-la-eleccion-del-consejo-constitucional-7325",
  "https://fundacionsol.cl/blog/actualidad-13/post/ley-de-las-40-horas-el-caballo-de-troya-de-la-flexibilidad-laboral-7323",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-minimo-insuficiencia-y-arbitrariedad-7321",
  "https://fundacionsol.cl/blog/actualidad-13/post/bancos-y-concentracion-de-poder-en-chile-7250",
  "https://fundacionsol.cl/blog/actualidad-13/post/8m-sindicalizadas-6917",
  "https://fundacionsol.cl/blog/actualidad-13/post/50-anos-del-golpe-8m-y-memoria-disidente-6918",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-economia-y-las-contradicciones-del-modelo-chileno-6923",
  "https://fundacionsol.cl/blog/actualidad-13/post/privilegio-cis-6922",
  "https://fundacionsol.cl/blog/actualidad-13/post/inflacion-de-12-8-anual-como-impacta-y-como-contrarrestarla-6926",
  "https://fundacionsol.cl/blog/actualidad-13/post/pgu-y-mujeres-el-desconocimiento-a-las-labores-de-cuidado-7079",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuantos-empleos-faltan-para-estar-en-el-mismo-nivel-previo-a-la-pandemia-6927",
  "https://fundacionsol.cl/blog/actualidad-13/post/informal-endeble-o-protegido-que-tipo-de-empleo-tiene-usted-6928",
  "https://fundacionsol.cl/blog/actualidad-13/post/tiempo-robado-7084",
  "https://fundacionsol.cl/blog/actualidad-13/post/negociacion-colectiva-para-el-momento-actual-6930",
  "https://fundacionsol.cl/blog/actualidad-13/post/proyecto-de-40-horas-la-necesidad-de-fortalecer-a-los-sindicatos-y-su-negociacion-colectiva-7088",
  "https://fundacionsol.cl/blog/actualidad-13/post/empleo-en-chile-6931",
  "https://fundacionsol.cl/blog/actualidad-13/post/contra-el-tpp-11-y-en-defensa-del-buen-vivir-6932",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuanto-y-a-quienes-financia-el-gran-empresariado-en-este-plebiscito-6933",
  "https://fundacionsol.cl/blog/actualidad-13/post/inflacion-6934",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-minimo-y-justicia-de-genero-6943",
  "https://fundacionsol.cl/blog/actualidad-13/post/5-horas-menos-de-trabajo-son-suficientes-6936",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-urgencia-de-una-reforma-estructural-al-sistema-de-pensiones-chileno-6937",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajadores-y-accion-sindical-el-debate-al-margen-en-la-convencion-6938",
  "https://fundacionsol.cl/blog/actualidad-13/post/crisis-de-cuidados-producir-lo-necesario-redistribuirlo-todo-6939",
  "https://fundacionsol.cl/blog/actualidad-13/post/en-este-8-de-marzo-abajo-el-capitalismo-6940",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajadores-en-tiempo-de-crisis-organizate-porque-tutrabajovale-6967",
  "https://fundacionsol.cl/blog/actualidad-13/post/pension-garantizada-universal-o-fortalecimiento-del-pilar-solidario-7308",
  "https://fundacionsol.cl/blog/actualidad-13/post/repensando-la-accion-sindical-en-la-constitucion-7274",
  "https://fundacionsol.cl/blog/actualidad-13/post/1o-de-mayo-por-una-renta-basica-universal-de-emergencia-6945",
  "https://fundacionsol.cl/blog/actualidad-13/post/deuda-y-consumo-el-desequilibrio-en-los-hogares-7277",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-4-caras-del-mundo-del-trabajo-6946",
  "https://fundacionsol.cl/blog/actualidad-13/post/que-la-solidaridad-se-haga-costumbre-por-un-sistema-de-reparto-para-chile-6947",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-modelo-chileno-amenazado-pero-aun-intacto-7273",
  "https://fundacionsol.cl/blog/actualidad-13/post/extractivismo-y-afp-desposesion-territorial-para-beneficio-del-capital-6949",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-crisis-del-trabajo-detras-de-la-revuelta-chilena-6948",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-resistencia-de-un-pueblo-endeudado-7044",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-acuerdo-por-el-trabajo-flexible-7099",
  "https://fundacionsol.cl/blog/actualidad-13/post/postnatal-de-emergencia-e-indolencia-del-gobierno-7100",
  "https://fundacionsol.cl/blog/actualidad-13/post/un-acuerdo-para-quien-7101",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-endeble-red-de-proteccion-del-gobierno-7103",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuarentena-con-100-lucas-y-la-dignidad-de-los-hogares-chilenos-7104",
  "https://fundacionsol.cl/blog/actualidad-13/post/dia-de-la-madre-y-trabajo-invisibilizado-7105",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-corralito-legal-de-las-afp-para-los-grandes-grupos-economicos-7106",
  "https://fundacionsol.cl/blog/actualidad-13/post/covid-19-y-la-mirada-mercantil-del-gobierno-7107",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-coronavirus-en-adultos-mayores-hace-explotar-la-basura-debajo-de-la-alfombra-del-sistema-de-salud-7108",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-crisis-que-sostienen-las-mujeres-7109",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-dignidad-del-trabajo-en-tiempos-de-covid-19-7110",
  "https://fundacionsol.cl/blog/actualidad-13/post/por-que-el-plan-economico-ante-el-covid-19-es-insuficiente-y-lo-agrava-el-dictamen-que-permite-no-pagar-remuneraciones-7111",
  "https://fundacionsol.cl/blog/actualidad-13/post/pensiones-sin-seguridad-social-7102",
  "https://fundacionsol.cl/blog/actualidad-13/post/quien-cuida-a-las-que-cuidan-7113",
  "https://fundacionsol.cl/blog/actualidad-13/post/capitalismo-en-crisis-y-una-cuarentena-urgente-7112",
  "https://fundacionsol.cl/blog/actualidad-13/post/no-somos-iguales-la-explotacion-de-las-mujeres-empobrecidas-7114",
  "https://fundacionsol.cl/blog/actualidad-13/post/ya-viene-marzo-la-zanahoria-y-el-garrote-7115",
  "https://fundacionsol.cl/blog/actualidad-13/post/hasta-que-la-vida-valga-la-pena-3960",
  "https://fundacionsol.cl/blog/actualidad-13/post/bajos-sueldos-y-brecha-de-genero-que-hacer-7120",
  "https://fundacionsol.cl/blog/actualidad-13/post/chiledesperto-la-crisis-de-la-vida-la-dignidad-de-la-revuelta-7118",
  "https://fundacionsol.cl/blog/actualidad-13/post/de-pie-cantar-7117",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-milagro-chileno-en-llamas-7116",
  "https://fundacionsol.cl/blog/actualidad-13/post/mas-de-15-muertos-y-el-modelo-no-se-toca-7119",
  "https://fundacionsol.cl/blog/actualidad-13/post/flexibilidad-laboral-a-la-medida-de-quien-7122",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-en-el-ano-2101-que-pasara-con-las-pensiones-3951",
  "https://fundacionsol.cl/blog/actualidad-13/post/sobre-40-horas-flexibilidad-precarizante-y-la-falacia-de-la-igualdad-de-condiciones-entre-trabajo-y-capital-3941",
  "https://fundacionsol.cl/blog/actualidad-13/post/mejor-salud-para-el-capital-7121",
  "https://fundacionsol.cl/blog/actualidad-13/post/endeudamiento-y-mujeres-la-ultima-frontera-de-la-explotacion-7123",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-afp-y-los-imperios-del-dinero-7124",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-agenda-laboral-del-capital-es-flexible-el-trabajo-en-chile-7125",
  "https://fundacionsol.cl/blog/actualidad-13/post/contar-sindicatos-o-sindicatos-que-cuentan-7127",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-5-patas-del-gato-luksic-7128",
  "https://fundacionsol.cl/blog/actualidad-13/post/afp-las-pensiones-del-tercer-mundo-y-la-capitalizacion-del-mundo-desarrollado-7129",
  "https://fundacionsol.cl/blog/actualidad-13/post/estadios-de-miseria-la-cruda-realidad-de-jubilar-en-chile-7130",
  "https://fundacionsol.cl/blog/actualidad-13/post/por-la-necesidad-de-manifestarse-7131",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-al-sistema-de-pensiones-del-gobierno-de-pinera-i-el-fracaso-de-las-afp-y-las-cuentas-individuales-7132",
  "https://fundacionsol.cl/blog/actualidad-13/post/8-de-marzo-por-el-derecho-a-la-pausa-7133",
  "https://fundacionsol.cl/blog/actualidad-13/post/y-si-miramos-la-pobreza-de-mercado-las-trampas-del-famoso-alquiler-imputado-7134",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-aborto-es-justicia-social-7135",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-reformas-del-capital-y-el-dia-del-trabajo-7136",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-degradacion-estructural-del-empleo-publico-7140",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-huelga-del-trabajo-invisible-7139",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-mujeres-y-las-necesidades-del-capitalismo-historico-7138",
  "https://fundacionsol.cl/blog/actualidad-13/post/para-no-olvidar-en-este-8m-la-crisis-estructural-del-capitalismo-patriarcal-7137",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-ciclo-largo-de-la-deuda-y-la-coyuntura-economica-actual-7142",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-en-el-top-ten-mundial-otra-mirada-a-la-comparacion-de-esquemas-previsionales-7141",
  "https://fundacionsol.cl/blog/actualidad-13/post/subempleo-la-precariedad-que-mantiene-frenada-la-tasa-de-desocupacion-7164",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-afp-y-el-largo-plazo-la-papa-caliente-de-la-segunda-vuelta-7162",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-chile-moderno-de-los-grupos-economicos-7309",
  "https://fundacionsol.cl/blog/actualidad-13/post/pobreza-y-despojo-ancestral-7161",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-dictadura-y-los-limites-de-la-tolerancia-7160",
  "https://fundacionsol.cl/blog/actualidad-13/post/15-razones-para-votar-en-el-plebiscito-no-vinculante-sobre-el-sistema-de-pensiones-7158",
  "https://fundacionsol.cl/blog/actualidad-13/post/afp-y-buenas-pensiones-una-ecuacion-imposible-7157",
  "https://fundacionsol.cl/blog/actualidad-13/post/enel-precarizacion-laboral-que-nos-afecta-a-todos-as-7156",
  "https://fundacionsol.cl/blog/actualidad-13/post/s-p-el-gato-cuidando-la-carniceria-7155",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-minimo-de-270-000-caracol-tipo-jaguar-7154",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajo-y-deuda-los-grandes-ausentes-de-los-debates-y-entrevistas-presidenciales-7153",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-inactividad-femenina-y-su-impacto-en-el-empleo-7152",
  "https://fundacionsol.cl/blog/actualidad-13/post/que-crece-cuando-crece-el-empleo-por-cuenta-propia-7151",
  "https://fundacionsol.cl/blog/actualidad-13/post/por-que-el-cae-es-un-mecanismo-de-desposesion-expropiacion-financiera-7150",
  "https://fundacionsol.cl/blog/actualidad-13/post/cual-crisis-los-grupos-economicos-siguen-ganando-a-manos-llenas-7149",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-sueldos-que-se-pagan-en-chile-no-alcanzan-para-vivir-en-chile-7163",
  "https://fundacionsol.cl/blog/actualidad-13/post/3-puntos-para-un-cara-a-cara-entre-la-propuesta-del-gobierno-y-la-de-los-trabajadores-7165",
  "https://fundacionsol.cl/blog/actualidad-13/post/ni-5-ni-mas-anos-un-cambio-de-sistema-es-necesario-7159",
  "https://fundacionsol.cl/blog/actualidad-13/post/cordones-industriales-y-experiencias-de-autogestion-territorial-y-productiva-en-tiempos-de-la-unidad-popular-7144",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-deuda-de-los-hogares-y-las-movilizaciones-de-los-trabajadores-7166",
  "https://fundacionsol.cl/blog/actualidad-13/post/diez-razones-para-sumarse-a-la-marcha-no-afp-7167",
  "https://fundacionsol.cl/blog/actualidad-13/post/explotacion-trabajo-y-familia-7168",
  "https://fundacionsol.cl/blog/actualidad-13/post/en-este-dia-de-la-mujer-a-visibilizar-el-trabajo-7148",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-maule-golpeado-por-algo-mas-que-el-fuego-7147",
  "https://fundacionsol.cl/blog/actualidad-13/post/afp-y-pilar-solidario-7146",
  "https://fundacionsol.cl/blog/actualidad-13/post/pobreza-en-chile-a-la-luz-de-la-casen-2015-es-peor-de-lo-que-se-piensa-7145",
  "https://fundacionsol.cl/blog/actualidad-13/post/quien-paga-en-el-mercado-laboral-7170",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-formacion-de-salarios-y-el-papel-del-sector-publico-7172",
  "https://fundacionsol.cl/blog/actualidad-13/post/paro-no-afp-y-el-futuro-de-la-seguridad-social-7173",
  "https://fundacionsol.cl/blog/actualidad-13/post/empleo-por-cuenta-propia-y-el-mito-del-emprendimiento-7174",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-dura-realidad-de-las-pensiones-de-las-mujeres-7175",
  "https://fundacionsol.cl/blog/actualidad-13/post/ferraris-o-pensiones-la-desigualdad-una-vez-mas-7176",
  "https://fundacionsol.cl/blog/actualidad-13/post/cae-un-error-de-calculo-garrafal-7177",
  "https://fundacionsol.cl/blog/actualidad-13/post/elecciones-de-la-cut-y-la-aspiracion-democratica-7178",
  "https://fundacionsol.cl/blog/actualidad-13/post/apuntes-sobre-una-ciudadania-antipopular-7179",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-legitimidad-de-las-afp-entre-el-pecado-original-y-la-culpa-7180",
  "https://fundacionsol.cl/blog/actualidad-13/post/a-quien-sirve-el-negocio-de-las-afp-7182",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-tiempos-de-la-deuda-7183",
  "https://fundacionsol.cl/blog/actualidad-13/post/sindicatos-pulverizados-y-la-contradictoria-reforma-laboral-7184",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-laboral-y-tribunal-constitucional-una-rutina-de-humor-negro-7185",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-brutal-endeudamiento-de-los-chilenos-y-la-desposesion-salarial-7186",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-laboral-el-debate-que-no-fue-sobre-los-derechos-de-los-trabajadores-7187",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-laboral-con-sesgo-empresarial-7169",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-contradicciones-del-proyecto-laboral-de-la-nueva-mayoria-7188",
  "https://fundacionsol.cl/blog/actualidad-13/post/gratuidad-para-las-empresas-de-la-educacion-superior-los-limites-del-estado-neoliberal-7189",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-verdaderos-sueldos-del-sector-publico-7190",
  "https://fundacionsol.cl/blog/actualidad-13/post/endeudar-para-gobernar-y-mercantilizar-el-caso-del-cae-7191",
  "https://fundacionsol.cl/blog/actualidad-13/post/a-cuantos-trabajadores-se-quiere-sacar-de-la-reforma-laboral-7192",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-deuda-con-los-trabajadores-a-36-anos-del-plan-laboral-7193",
  "https://fundacionsol.cl/blog/actualidad-13/post/resistencia-del-mercado-laboral-o-resistencia-de-la-fuerza-de-trabajo-7194",
  "https://fundacionsol.cl/blog/actualidad-13/post/bancoestado-se-viene-el-cuco-del-sindicato-7195",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-laboral-menos-tecnica-y-mas-politica-7196",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-dictadura-del-capital-el-legado-vigente-de-pinochet-7310",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajadores-de-primera-y-segunda-categoria-la-externalizacion-como-desposesion-7197",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-huelga-mutilada-que-gusta-en-chile-7198",
  "https://fundacionsol.cl/blog/actualidad-13/post/subcontratistas-del-cobre-violencia-y-lucha-por-dignidad-7199",
  "https://fundacionsol.cl/blog/actualidad-13/post/241-000-un-salario-minimo-en-la-medida-de-lo-posible-7200",
  "https://fundacionsol.cl/blog/actualidad-13/post/por-que-el-miedo-de-los-empresarios-y-autoridades-a-la-negociacion-colectiva-por-rama-7201",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajar-en-una-economia-de-la-deuda-7202",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-hamburguesa-futbolera-y-el-chile-donde-la-mitad-gana-menos-de-5-000-diarios-7205",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-polemica-hipoteca-de-los-viejos-y-la-precariedad-de-las-jubilaciones-en-chile-7203",
  "https://fundacionsol.cl/blog/actualidad-13/post/inactividad-y-desposesion-lo-que-revela-el-mundo-de-los-jubilados-que-siguen-trabajando-7206",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-trasfondo-ideologico-del-paro-docente-quien-tiene-la-razon-quien-tiene-la-culpa-7204",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-mito-del-derecho-a-huelga-efectivo-con-la-reforma-7207",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-nueva-mayoria-y-el-espiritu-de-las-reformas-7208",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-posiciones-enfrentadas-en-la-reforma-laboral-7210",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-laboral-y-la-democracia-al-servicio-del-capital-7212",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-desafios-del-trabajo-del-siglo-xxi-7211",
  "https://fundacionsol.cl/blog/actualidad-13/post/negociacion-colectiva-ramal-el-verdadero-mecanismo-para-distribuir-ingresos-que-el-establishment-evita-7215",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-empresarios-y-el-conflicto-bajo-la-alfombra-7214",
  "https://fundacionsol.cl/blog/actualidad-13/post/boletariado-platas-frescas-para-las-afp-7213",
  "https://fundacionsol.cl/blog/actualidad-13/post/penta-y-el-cartel-de-la-acumulacion-7216",
  "https://fundacionsol.cl/blog/actualidad-13/post/mercado-legislativo-y-plutocracia-7217",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-gallina-de-los-huevos-de-oro-de-los-empresarios-7218",
  "https://fundacionsol.cl/blog/actualidad-13/post/interrogando-a-la-desaceleracion-quien-decrece-cuando-chile-decrece-7220",
  "https://fundacionsol.cl/blog/actualidad-13/post/deuda-y-derechos-sociales-el-subsidio-al-capital-7219",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-super-ricos-y-la-mercantilizacion-de-la-vida-7221",
  "https://fundacionsol.cl/blog/actualidad-13/post/calidad-del-empleo-el-efecto-de-los-derechos-colectivos-del-trabajo-7222",
  "https://fundacionsol.cl/blog/actualidad-13/post/relaciones-laborales-reforma-y-patologia-del-conflicto-7223",
  "https://fundacionsol.cl/blog/actualidad-13/post/una-cascada-de-pensiones-miserables-7224",
  "https://fundacionsol.cl/blog/actualidad-13/post/banqueros-con-el-derecho-de-acumular-en-paz-7225",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-nostalgica-rigidez-del-mundo-del-trabajo-7226",
  "https://fundacionsol.cl/blog/actualidad-13/post/hospital-del-salvador-y-la-lucha-por-el-fin-de-las-concesiones-hospitalarias-7227",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-democracia-fragmentada-7228",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuando-el-trabajo-se-quema-a-lo-bonzo-7229",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-trabajadores-independientes-mas-alla-de-la-ideologia-del-emprendimiento-7230",
  "https://fundacionsol.cl/blog/actualidad-13/post/a-35-anos-del-plan-laboral-su-reforma-ya-esta-escrita-7231",
  "https://fundacionsol.cl/blog/actualidad-13/post/otro-ano-del-plan-laboral-no-hay-nada-que-festejar-7232",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-una-democracia-funcional-al-capital-7233",
  "https://fundacionsol.cl/blog/actualidad-13/post/educacion-publica-en-la-medida-de-lo-posible-7235",
  "https://fundacionsol.cl/blog/actualidad-13/post/alto-hospicio-la-contradiccion-de-vivir-tan-cerca-y-tan-lejos-de-la-principal-riqueza-de-chile-7249",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-chorreo-del-credito-y-la-ilusion-de-la-clase-media-7236",
  "https://fundacionsol.cl/blog/actualidad-13/post/educacion-financiera-deficitaria-o-la-apropiacion-del-valor-del-trabajo-7238",
  "https://fundacionsol.cl/blog/actualidad-13/post/sistema-de-afp-trabajadores-golpean-donde-empresarios-y-gobierno-callan-7244",
  "https://fundacionsol.cl/blog/actualidad-13/post/y-cuando-sera-realmente-el-dia-de-los-trabajadores-7245",
  "https://fundacionsol.cl/blog/actualidad-13/post/freno-al-multirut-un-pequeno-paso-para-los-trabajadores-7246",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-famosa-clase-media-donde-esta-7248",
  "https://fundacionsol.cl/blog/actualidad-13/post/incendio-en-valparaiso-el-estado-minimo-frente-al-patrimonio-cultural-7247",
  "https://fundacionsol.cl/blog/actualidad-13/post/negociacion-colectiva-por-rama-si-pero-no-cualquiera-7252",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-tributaria-accion-fiscal-para-redistribuir-ingresos-7254",
  "https://fundacionsol.cl/blog/actualidad-13/post/subcontratacion-el-giro-principal-de-la-educacion-7255",
  "https://fundacionsol.cl/blog/actualidad-13/post/viejos-conflictos-para-nuevas-estructuras-sociales-7256",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-salud-no-es-solo-un-tema-de-expertos-7257",
  "https://fundacionsol.cl/blog/actualidad-13/post/reforma-tributaria-la-ilusion-de-una-redistribucion-duradera-del-ingreso-7237",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-la-ocde-y-la-desigualdad-de-ingresos-el-baile-de-los-que-sobran-7259",
  "https://fundacionsol.cl/blog/actualidad-13/post/empleos-precarios-la-cara-oculta-del-exito-en-materia-laboral-7260",
  "https://fundacionsol.cl/blog/actualidad-13/post/bachelet-los-cambios-de-fondo-no-estan-en-trabajo-7316",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-futuro-del-plan-laboral-de-la-dictadura-7307",
  "https://fundacionsol.cl/blog/actualidad-13/post/casen-la-pobreza-el-modelo-y-el-fracaso-de-la-elite-7272",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-garrote-y-la-zanahoria-detras-del-actual-orden-del-trabajo-7315",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-la-hegemonia-del-capital-financiero-y-la-crisis-del-trabajo-7314",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-limites-de-nuestra-negociacion-colectiva-y-la-formalidad-precarizante-7261",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-reinvencion-del-capitalismo-7313",
  "https://fundacionsol.cl/blog/actualidad-13/post/desigualdad-y-terrorismo-laboral-7312",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-minimo-de-205-000-seguimos-echando-la-tierra-debajo-de-la-alfombra-7305",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-dia-de-la-felicidad-y-nuestras-condiciones-materiales-de-vida-7311",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-retorica-de-la-felicidad-y-los-trabajadores-pobres-7291",
  "https://fundacionsol.cl/blog/actualidad-13/post/cuando-la-forma-se-comio-al-fondo-la-meta-del-millon-de-empleos-7271",
  "https://fundacionsol.cl/blog/actualidad-13/post/y-a-usted-le-sobra-la-plata-7304",
  "https://fundacionsol.cl/blog/actualidad-13/post/precariedad-laboral-y-seduccion-empresarial-una-vuelta-al-siglo-xix-7292",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-problemas-de-un-sistema-tributario-pensado-para-favorecer-a-las-elites-7262",
  "https://fundacionsol.cl/blog/actualidad-13/post/pib-per-capita-de-16-mil-dolares-nos-quejamos-de-llenos-7278",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-patron-de-fundo-historias-de-nanas-impuestos-desalojo-de-la-educacion-publica-y-bajos-salarios-7303",
  "https://fundacionsol.cl/blog/actualidad-13/post/contra-la-desigualdad-la-negociacion-colectiva-es-la-clave-7263",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-trabajo-me-quita-la-vida-7276",
  "https://fundacionsol.cl/blog/actualidad-13/post/en-chile-esta-mal-pelao-el-chancho-7302",
  "https://fundacionsol.cl/blog/actualidad-13/post/chile-y-la-sociedad-20-80-cronica-de-una-muerte-anunciada-7290",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-casta-de-las-4-mil-familias-que-tienen-secuestrado-al-pais-7301",
  "https://fundacionsol.cl/blog/actualidad-13/post/tapando-el-sol-con-el-dedo-el-discurso-de-la-flexibilidad-laboral-7289",
  "https://fundacionsol.cl/blog/actualidad-13/post/trabajo-decente-y-la-meta-del-millon-de-empleos-7298",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-4-mil-familias-que-viven-en-el-mundo-de-bilz-y-pap-7275",
  "https://fundacionsol.cl/blog/actualidad-13/post/lo-que-nos-va-quedando-del-sistema-de-educacion-mixto-7279",
  "https://fundacionsol.cl/blog/actualidad-13/post/huelga-de-hambre-en-starbucks-un-cafe-amargo-que-no-chorrea-7297",
  "https://fundacionsol.cl/blog/actualidad-13/post/dos-holdings-de-educacion-superior-concentran-mas-alumnos-que-16-universidades-estatales-7280",
  "https://fundacionsol.cl/blog/actualidad-13/post/reajuste-al-salario-minimo-la-clase-politica-nuevamente-no-dio-el-ancho-7296",
  "https://fundacionsol.cl/blog/actualidad-13/post/los-subempleados-de-chile-un-record-oculto-7264",
  "https://fundacionsol.cl/blog/actualidad-13/post/alcanzando-el-sueldo-minimo-vital-en-2090-2832",
  "https://fundacionsol.cl/blog/actualidad-13/post/el-salario-minimo-y-los-jovenes-una-respuesta-a-libertad-y-desarrollo-7265",
  "https://fundacionsol.cl/blog/actualidad-13/post/como-atrapar-las-moscas-con-la-miel-y-pagar-el-menor-sueldo-posible-7288",
  "https://fundacionsol.cl/blog/actualidad-13/post/decide-usted-o-deciden-los-de-siempre-7295",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-minimo-y-la-historia-no-contada-de-las-presiones-inflacionarias-7266",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-increible-situacion-de-la-educacion-publica-en-chile-7294",
  "https://fundacionsol.cl/blog/actualidad-13/post/pan-para-hoy-hambre-para-manana-7293",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-sombra-del-trabajo-en-el-1o-de-mayo-7287",
  "https://fundacionsol.cl/blog/actualidad-13/post/las-empresas-y-el-trabajo-voraz-7286",
  "https://fundacionsol.cl/blog/actualidad-13/post/salario-emocional-y-gestion-de-la-felicidad-7285",
  "https://fundacionsol.cl/blog/actualidad-13/post/todos-a-trabajar-y-unos-pocos-con-empleo-7281",
  "https://fundacionsol.cl/blog/actualidad-13/post/siete-mil-escuelas-publicas-de-excelencia-para-2014-7282",
  "https://fundacionsol.cl/blog/actualidad-13/post/2011-el-ano-para-debatir-sobre-la-calidad-del-empleo-7283",
  "https://fundacionsol.cl/blog/actualidad-13/post/la-hipocresia-de-llamar-a-los-trabajadores-colaboradores-7284",
  "https://fundacionsol.cl/blog/actualidad-13/post/no-estamos-bien-en-el-jumbo-los-14-000-7269",
  "https://fundacionsol.cl/blog/actualidad-13/post/huelga-en-farmacias-ahumada-los-calculos-de-los-trabajadores-que-exigen-gratificacion-7268"
)

datos_totales <- data.frame()

for (i in 1:length(enlaces)) {
  url <- enlaces[i]
  
  mensaje_progreso <- paste("Extrayendo datos del enlace", i, "de", length(enlaces))
  print(mensaje_progreso)
  
  pagina <- read_html(url)
  
  titulo <- pagina %>% html_node("meta[property='og:title']") %>% html_attr("content")
  fecha_publicacion <- pagina %>% html_node("meta[property='article:published_time']") %>% html_attr("content")
  medio_comunicacion <- pagina %>% html_node("meta[property='og:description']") %>% html_attr("content")
  autor <- pagina %>% html_node("#o_wblog_post_content > div.o_wblog_post_content_field.o_wblog_read_text > p:nth-child(2)") %>% html_text()
  etiquetas <- pagina %>% html_nodes("meta[property^='article:tag']") %>% html_attr("content") %>% paste(collapse = ", ")
  
  datos_enlace <- data.frame(Título = titulo,
                             `Fecha de publicación` = fecha_publicacion,
                             `Medio de comunicación` = medio_comunicacion,
                             Autor = autor,
                             Etiquetas = etiquetas)
  
  datos_totales <- rbind(datos_totales, datos_enlace)
}

nombre_archivo <- "FS Opinión.xlsx"
write.xlsx(datos_totales, file = nombre_archivo, row.names = FALSE)

mensaje_final <- paste("Los datos se han extraído correctamente y se han guardado en el archivo", nombre_archivo)
print(mensaje_final)
