# ---*** R10 CODES ***--- N°41

enlaces <- c(
  "https://chile21.cl/china-en-el-tablero-mundial-y-su-relacion-con-america-latina/",
  "https://chile21.cl/chile21-reune-a-expertos-para-debatir-la-politica-indigena-y-el-conflicto-estado-pueblo-mapuche/",
  "https://chile21.cl/alejandra-krauss-este-pais-se-merece-un-texto-constitucional-nacido-en-democracia/",
  "https://chile21.cl/pinochet-recupera-imagen-y-la-dictadura-no-es-condenada-unanimemente-segun-barometro-cerc-mori-1987-2023/",
  "https://chile21.cl/ministro-de-justicia-encabezo-conversatorio-sobre-carceles-en-chile21/",
  "https://chile21.cl/el-origen-de-la-violencia-que-es-lo-que-causa-tanta-irritabilidad-en-los-chilenos/",
  "https://chile21.cl/nuevo-director-de-chile-21-nos-gustaria-que-la-alianza-entre-apruebo-dignidad-y-el-socialismo-democratico-fuese-mas-estable/",
  "https://chile21.cl/actividades-2020-y-2021/",
  "https://chile21.cl/balances-2020-y-2021/",
  "https://chile21.cl/fundacion-chile-21-llama-a-votar-apruebo/",
  "https://chile21.cl/contraste-constituyente-48/",
  "https://chile21.cl/contraste-constituyente-47/",
  "https://chile21.cl/contraste-constituyente-46/",
  "https://chile21.cl/contraste-constituyente-45/",
  "https://chile21.cl/contraste-constituyente-44/",
  "https://chile21.cl/contraste-constituyente-43/",
  "https://chile21.cl/contraste-constituyente-42/",
  "https://chile21.cl/contraste-constituyente-40-2/",
  "https://chile21.cl/contraste-constituyente-40/",
  "https://chile21.cl/contraste-constituyente-39/",
  "https://chile21.cl/contraste-constituyente-38/",
  "https://chile21.cl/seminario-movimientos-sociales-y-partidos-politicos/",
  "https://chile21.cl/contraste-constituyente-37/",
  "https://chile21.cl/contraste-constituyente-36/",
  "https://chile21.cl/contraste-constituyente-35/",
  "https://chile21.cl/contraste-constituyente-34/",
  "https://chile21.cl/contraste-constituyente-33/",
  "https://chile21.cl/contraste-constituyente-32/",
  "https://chile21.cl/contraste-constituyente-31/",
  "https://chile21.cl/contraste-constituyente-30/",
  "https://chile21.cl/contraste-constituyente-29/",
  "https://chile21.cl/contraste-constituyente-27-2/",
  "https://chile21.cl/contraste-constituyente-27/",
  "https://chile21.cl/contraste-constituyente-26/",
  "https://chile21.cl/contraste-constituyente-25/",
  "https://chile21.cl/contraste-constituyente-24/",
  "https://chile21.cl/la-era-boric-chile-en-el-foco-mundial/",
  "https://chile21.cl/hacia-una-nueva-educacion-publica-desafio-clave-para-el-nuevo-gobierno/",
  "https://chile21.cl/contraste-constituyente-23/",
  "https://chile21.cl/contraste-constituyente-22/",
  "https://chile21.cl/informe-diciembre-contrasteschile21/",
  "https://chile21.cl/contraste-constituyente-21/",
  "https://chile21.cl/contraste-constituyente-20/",
  "https://chile21.cl/contraste-constituyente-19/",
  "https://chile21.cl/contraste-constituyente-edicionespecial-2/",
  "https://chile21.cl/contraste-constituyente-18/",
  "https://chile21.cl/analisis-de-los-programas-de-gobierno-en-educacion-de-las-candidaturas-de-centro-izquierda/",
  "https://chile21.cl/contraste-constituyente-17/",
  "https://chile21.cl/debate-analisis-de-programas-presidenciales-de-cultura/",
  "https://chile21.cl/constraste-constituyente-16/",
  "https://chile21.cl/constraste-constituyente-15/",
  "https://chile21.cl/el-relativismo-historico-puede-conducir-al-fascismo/",
  "https://chile21.cl/el-trabajo-en-la-nueva-constitucion-presentacion-documental-del-area-laboral-de-chile-21/",
  "https://chile21.cl/contraste-constituyente-edicionespecial/",
  "https://chile21.cl/contraste-constituyente-14/",
  "https://chile21.cl/constraste-constituyente-13/",
  "https://chile21.cl/hasta-que-la-dignidad-sea-un-derecho/",
  "https://chile21.cl/contraste-constituyente-12/",
  "https://chile21.cl/constrastes-constituyentes-11/",
  "https://chile21.cl/contraste-constituyente-10/",
  "https://chile21.cl/el-descaro-pinera-y-allamand-se-van-a-europa/",
  "https://chile21.cl/constrastes-constituyentes-8/",
  "https://chile21.cl/contraste-constituyente-7/",
  "https://chile21.cl/conversatorio-el-trabajo-en-la-nueva-constitucion/",
  "https://chile21.cl/contraste-constituyente-6/",
  "https://chile21.cl/foro-programatico-de-unidad-constituyente-propuestas-presidenciales-de-ciudad-y-territorio/",
  "https://chile21.cl/politicas-de-comunicacion-para-una-nueva-era-en-chile-de-la-concentracion-al-pluralismo-mediatico/",
  "https://chile21.cl/trabajo-en-la-nueva-constitucion/",
  "https://chile21.cl/presidenta-de-chile-21-participa-de-elaboracion-de-informe-propuesta-constitucional-del-mundo-sindical/",
  "https://chile21.cl/seminariola-politica-de-defensa-de-chile-analisis-y-observaciones/",
  "https://chile21.cl/mientras-en-la-oposicion-haya-candidatos-enfocados-en-fortalecer-su-identidad-sera-imposible-un-proyecto-comun/",
  "https://chile21.cl/la-nueva-constitucion-mirando-al-futuro-presentacion-del-libro-el-gran-giro-de-america-latina/",
  "https://chile21.cl/ffaa-y-seguridad-interna-los-limites-necesarios/",
  "https://chile21.cl/y-despues-de-mayo-que-corrientes-de-opinion-y-fuerzas-politicas-en-los-nuevos-mapas-electorales/",
  "https://chile21.cl/recursos-naturales-y-asamblea-constituyente-el-caso-de-la-ley-de-pesca/",
  "https://chile21.cl/violencia-y-seguridad-ciudadana-nuevas-perspectivas-de-analisis-y-politicas-publicas/",
  "https://chile21.cl/la-autonomia-de-las-fuerzas-armadas-en-chile/",
  "https://chile21.cl/participacion-y-transparencia-en-la-nueva-constitucion/",
  "https://chile21.cl/regreso-de-lula-cual-es-el-nuevo-cuadro-politico-en-brasil/",
  "https://chile21.cl/taller-de-coyuntura-con-paula-narvaez/",
  "https://chile21.cl/derechos-cultura-y-enfoque-de-genero-en-la-nueva-constitucion/",
  "https://chile21.cl/chile-21-nombrado-3er-think-tank-mas-influyente-en-chile-y-22-en-la-region/",
  "https://chile21.cl/deliberacion-publica-de-cara-al-2021/",
  "https://chile21.cl/todo-lo-que-quisiste-saber-sobre-el-dhont-y-no-te-animaste-a-preguntar/",
  "https://chile21.cl/en-la-previa-a-la-inauguracion-de-joe-biden-como-presidente-de-eeuu/",
  "https://chile21.cl/a-pesar-de-las-excusas-y-falta-de-voluntad-no-todo-esta-perdido/",
  "https://chile21.cl/la-oposicion-debate-sobre-un-banco-central-independiente/",
  "https://chile21.cl/desarmemoschile/",
  "https://chile21.cl/minimos-comunes-informe-presidencias-de-partidos/",
  "https://chile21.cl/educacion-y-pandemia-reflexiones-para-garantizar-el-derecho-a-la-educacion/",
  "https://chile21.cl/la-irrupcion-de-los-neuroderechos/",
  "https://chile21.cl/debate-candidatxs-primarias-gobernacion-rm/",
  "https://chile21.cl/primer-debate-amplio-de-gobernadorxs-primarias-rm/",
  "https://chile21.cl/nuevo-paradigma-una-constitucion-comprometida-con-la-cultura-la-ciencia-y-los-derechos-humanos/",
  "https://chile21.cl/analisis-y-proyeccion-de-los-resultados-del-plebiscito/",
  "https://chile21.cl/no-podemos-seguir-usando-la-condena-a-la-violencia-como-una-pildora-para-dormir-tranquilos/",
  "https://chile21.cl/video-nueva-constitucion-para-las-trabajadoras-y-trabajadores-de-chile/",
  "https://chile21.cl/justicia-ambiental-y-constitucion-la-mirada-de-las-zonas-de-sacrificio/",
  "https://chile21.cl/libertad-de-expresion-y-nueva-constitucion/",
  "https://chile21.cl/miradas-y-perspectivas-del-sector-cultural/",
  "https://chile21.cl/orden-publico-para-el-nuevo-chile-demostraciones-marchas-y-protestas/",
  "https://chile21.cl/eduardo-vergara-sobre-minimos-comunes-en-tvn24es-un-proceso-que-mira-hacia-la-ventana-proxima-de-elecciones-que-tendremos-en-chile/",
  "https://chile21.cl/el-mejor-plebiscito-del-mundo-2/",
  "https://chile21.cl/plebiscito-cuidado-con-las-noticias-falsas/",
  "https://chile21.cl/minimoscomunes/",
  "https://chile21.cl/hay-agua-para-una-constitucion-verde/",
  "https://chile21.cl/america-latina-tras-seis-meses-de-pandemia/",
  "https://chile21.cl/china-en-el-tablero-internacional-repercusiones-para-america-latina-y-el-caribe/",
  "https://chile21.cl/otra-mirada-a-50-anos-del-triunfo-de-salvador-allende/",
  "https://chile21.cl/eduardo-vergara-si-algunos-de-estos-7-generales-es-declarado-culpable-mario-rozas-y-los-ministros-blumel-y-perez-tambien-lo-son/",
  "https://chile21.cl/chile-21-lanza-observatorio-de-derechos-y-gobierno-digital/",
  "https://chile21.cl/de-la-fuente-la-ciudadania-no-cree-mas-en-el-camino-de-la-reforma-lo-que-pide-es-un-cambio-de-fondo/",
  "https://chile21.cl/proponen-protocolo-para-desescalar-violencia-en-el-contexto-del-plebiscito/",
  "https://chile21.cl/director-chile-21-el-modelo-de-ejecucion-del-orden-publico-de-hoy-escala-los-conflictos/",
  "https://chile21.cl/encuesta-de-chile-21-65-cree-que-el-plebiscito-se-desarrollara-con-incidentes/",
  "https://chile21.cl/cultura-en-la-nueva-constitucion-sentando-las-bases-necesarias-para-el-nuevo-chile/",
  "https://chile21.cl/desafios-para-la-integracion-de-america-latina-y-el-caribe-en-el-siglo-xxi/",
  "https://chile21.cl/una-conversacion-abierta-junto-al-senador-francisco-huenchumilla/",
  "https://chile21.cl/estudio-mundial-de-valores-2018-2020-el-cambio-valorico-en-chile/",
  "https://chile21.cl/elecciones-en-eeuu-efectos-para-america-latina-y-chile/",
  "https://chile21.cl/teletrabajo-impacto-en-las-y-los-trabajadores/",
  "https://chile21.cl/una-estrategia-para-el-plebiscito/",
  "https://chile21.cl/plebiscito-y-orden-publico-antes-durante-y-despues/",
  "https://chile21.cl/chile-el-capitan-araya-de-escazu/",
  "https://chile21.cl/agua/",
  "https://chile21.cl/documento-de-trabajo-plebiscito-para-una-nueva-constitucion/",
  "https://chile21.cl/plebiscito/",
  "https://chile21.cl/taller-de-coyuntura-una-conversacion-abierta-con-daniel-jadue/",
  "https://chile21.cl/datos-2/",
  "https://chile21.cl/dialogo-constitucional-crisis-y-plebiscito/",
  "https://chile21.cl/encuesta-fundacion-chile-21-82-cree-que-seguridad-publica-sigue-igual-o-peor-tras-implementacion-de-medidas-contra-covid-19/",
  "https://chile21.cl/dialogo-europa-y-america-latina-post-pandemia/",
  "https://chile21.cl/test/",
  "https://chile21.cl/pensiones/",
  "https://chile21.cl/exterior/",
  "https://chile21.cl/conversatorio-con-mujeres-indigenas-presente-y-futuro-de-los-derechos-indigenas/",
  "https://chile21.cl/hablemosseguridad-2/",
  "https://chile21.cl/se-siente-mas-seguro-con-militares-y-policias-en-la-pandemia-chile-21-prepara-big-data-sobre-la-fuerza-publica/",
  "https://chile21.cl/chilequeviene/",
  "https://chile21.cl/laboral/",
  "https://chile21.cl/laboral-2/",
  "https://chile21.cl/taller-de-coyuntura-con-senador-jose-miguel-insulza/",
  "https://chile21.cl/democracia/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-presidente-pinera-esta-aprovechando-la-situacion-para-impulsar-su-agenda-populista-de-mano-dura-en-el-congreso/",
  "https://chile21.cl/resulta-aventurado-e-irresponsanble-instalar-una-victoria-cuando-la-encuesta-de-seguridad-fue-aplicada-durante-el-estallido-social/",
  "https://chile21.cl/proteccion-al-consumidor-en-chile-lo-que-viene/",
  "https://chile21.cl/nacionales/",
  "https://chile21.cl/nueva-realidad-laboral-y-economica-en-tiempos-de-pandemia/",
  "https://chile21.cl/taller-de-coyuntura-con-senador-carlos-montes/",
  "https://chile21.cl/oposicion/",
  "https://chile21.cl/hablemosseguridad/",
  "https://chile21.cl/la-pandemia-y-las-transformaciones-del-siglo-xxi-la-democracia-en-tension/",
  "https://chile21.cl/migraciones/",
  "https://chile21.cl/comunicaciones/",
  "https://chile21.cl/datos/",
  "https://chile21.cl/ceroemision/",
  "https://chile21.cl/rol-de-la-oposicion-en-el-contexto-actual-junto-a-los-presidentes-de-las-juventudes/",
  "https://chile21.cl/bet-gerber-analiza-medios-y-crisis-en-programa-de-el-periodista/",
  "https://chile21.cl/empresas/",
  "https://chile21.cl/covid-19-donde-estamos-y-hacia-donde-vamos/",
  "https://chile21.cl/talleres-de-coyuntura/",
  "https://chile21.cl/economia/",
  "https://chile21.cl/una-salud-publica-chilena-post-crisis/",
  "https://chile21.cl/ciudad/",
  "https://chile21.cl/salud/",
  "https://chile21.cl/seguimiento-de-la-asignacion-de-recursos-para-proyectos-de-inversion-subdere-y-su-impacto-en-la-politica-local/",
  "https://chile21.cl/por-una-mayor-transparencia-en-la-emergencia-sanitaria-directora-de-modernizacion-del-estado-y-vice-presidenta-de-comision-de-gasto-publico-entrega-propuestas/",
  "https://chile21.cl/recalendarizacion-electoral-los-que-ganan-pierden-y-empatan/",
  "https://chile21.cl/el-principal-hito-climatico-para-chile-ha-sido-la-nueva-contribucion-nacional-que-compromete-cero-emisiones-netas-al-2050/",
  "https://chile21.cl/seguridadpandemia/",
  "https://chile21.cl/medio-ambiente-y-cambio-climatico-las-implicancias-ambientales-de-la-crisis-sanitaria/",
  "https://chile21.cl/pandemia-y-crisis-economica-global-la-situacion-actual/",
  "https://chile21.cl/6-medidas-inmediatas-para-enfrentar-el-coronavirus/",
  "https://chile21.cl/america-latina-es-la-region-mas-peligrosa-para-ser-activista-nuevo-estudio/",
  "https://chile21.cl/nuevo-estudio-resiliencia-democratica-activismo-politico-en-contextos-de-violencia/",
  "https://chile21.cl/chile-21-sube-al-puesto-22-regional-y-es-3ro-a-nivel-nacional-segun-global-think-tank-index-report/",
  "https://chile21.cl/eduardo-vergara-la-actitud-del-gobierno-es-que-esta-dejando-que-carabineros-llegue-al-borde-de-un-precipicio/",
  "https://chile21.cl/big-data-al-servicio-de-la-salud-y-la-medicina-personalizada/",
  "https://chile21.cl/gloria-de-la-fuente-en-programa-comando-jungle/",
  "https://chile21.cl/declaracion-centros-de-pensamiento/",
  "https://chile21.cl/una-breve-explicacion-sobre-el-narcotrafico-en-chile-el-enemigo-real-es-la-desigualdad/",
  "https://chile21.cl/eduardo-vergara-si-el-tono-de-carabineros-no-cambia-podemos-terminar-con-focos-con-verdaderas-guerras-civiles/",
  "https://chile21.cl/asamblea-constituyente-para-una-participacion-equitativa/",
  "https://chile21.cl/carabineros/",
  "https://chile21.cl/invitacion-crisis-social-y-desafios-ambientales-de-una-nueva-constitucion/",
  "https://chile21.cl/seria-impresentable-que-por-resguardar-un-evento-privado-con-fines-de-lucro-se-tengan-que-sacar-policias-de-barrios-transporte-publico-o-donde-la-gente-los-necesita/",
  "https://chile21.cl/%e2%98%9d%f0%9f%8f%bcminuta-chile-21-%f0%9f%9a%8c%f0%9f%9a%97%f0%9f%9a%9arenegociacion-de-tarifas-en-autopistas-urbanas-respecto-a-la-eliminacion-del-35-de-reajuste-a-peajes-en-autopistas-urbanas/",
  "https://chile21.cl/gabinete-sin-margen-un-plebiscito-urgente/",
  "https://chile21.cl/invitacion-homenaje-postumo-a-manfred-max-neef/",
  "https://chile21.cl/no-nos-pidan-que-lloremos-por-el-metro-si-no-han-sido-capaces-de-llorar-por-el-sufrimiento-de-generaciones-de-chilenos/",
  "https://chile21.cl/nuevademocracia/",
  "https://chile21.cl/invitacion-el-fenomeno-de-la-migracion-internacional-en-chile/",
  "https://chile21.cl/control-de-identidad-a-menores-de-edad-aprobarlo-es-retroceder-30-anos-en-proteccion-de-la-infancia/",
  "https://chile21.cl/la-estrategia-de-seguridad-del-gobierno-fracaso-subio-la-victimizacion-los-delitos-violentos-y-el-miedo/",
  "https://chile21.cl/presupuesto-seguridad-2020-subsecretaria-de-prevencion-del-delito/",
  "https://chile21.cl/informe-contraste-septiembre-2019/",
  "https://chile21.cl/invitacion-reforma-a-las-pensiones-y-equidad-de-genero-realidad-o-desafio/",
  "https://chile21.cl/impuestos-verdes-y-modernizacion-tributaria-la-justicia-ambiental-no-puede-esperar/",
  "https://chile21.cl/presidenta-de-chile-21-participa-en-coloquio-sobre-crisis-de-la-institucionalidad-politica/",
  "https://chile21.cl/ex-directora-de-chile-21-asume-rol-en-la-oficina-de-naciones-unidas-en-chile/",
  "https://chile21.cl/informeseguridad-seguridad-ciudadana-como-vamos/",
  "https://chile21.cl/propuesta-primarias-y-construccion-de-un-programa-comun/",
  "https://chile21.cl/seminario-propuestas-para-enfrentar-la-violencia-y-la-delincuencia-en-chile-21/",
  "https://chile21.cl/al-grano-ley-corta-antiterrorista/",
  "https://chile21.cl/conversatorio-habemus-reforma-previsional/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-ante-explosion-en-comisaria-la-deficiencia-es-algo-preocupante/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-me-parece-de-un-oportunismo-insultante-que-el-presidente-se-aproveche-para-pedir-apoyo-a-ampliar-ley-antiterrorista-y-justificar-participacion-de-militares/",
  "https://chile21.cl/presidenta-de-chile-21-asiste-a-primer-encuentro-de-trabajo-de-la-red-de-fundaciones-de-izquierda-y-progresista-de-america-latina/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-y-funcion-de-ff-aa-contra-el-narcotrafico-es-una-muestra-mas-de-una-politica-populista/",
  "https://chile21.cl/no-culpes-a-la-noche-director-ejecutivo-analiza-temas-de-narco-cultura-y-seguridad/",
  "https://chile21.cl/conversatorio-desafios-para-mejorar-la-calidad-de-vida-de-las-personas-y-el-crecimiento-economico-desde-la-perspectiva-de-la-infraestructura/",
  "https://chile21.cl/daniel-grimaldi-la-politica-efectista-de-pinera-sobre-venezuela-ha-fracasado/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-no-podemos-seguir-siendo-complices-del-populismo-de-la-mano-dura-y-el-control/",
  "https://chile21.cl/al-grano-descentralizacion-en-chile/",
  "https://chile21.cl/conversatorio-las-recientes-elecciones-generales-en-espana-ue-y-las-relaciones-europa-america-latina/",
  "https://chile21.cl/seminario-propuesta-de-reforma-al-empleo-publico-oportunidad-y-viabilidad/",
  "https://chile21.cl/conversatorio-realidad-y-desafios-del-nuevo-ciclo-electoral-2020-es-transparente-el-sistema-electoral-chileno/",
  "https://chile21.cl/junto-a-parlamentarios-del-fa-pc-ps-ppd-pr-alcalde-dc-y-otras-autoridades-chile-21-anuncia-proyecto-de-ley-para-control-de-armas-desarmemoschile/",
  "https://chile21.cl/eduardo-vergara-se-refiere-en-cnn-chile-sobre-seguridad-y-campana-desarmemoschile/",
  "https://chile21.cl/presidenta-de-chile-21-analiza-cuenta-publica-presidencial/",
  "https://chile21.cl/desarmemoschile-ex-presidente-lagos-se-suma-a-campana-de-chile-21-que-critica-a-pinera-en-seguridad/",
  "https://chile21.cl/director-del-area-de-economia-es-invitado-a-seminario-internacional-sobre-pensiones-organizado-por-la-comision-especial-para-la-reforma-de-prevision-social-de-la-camara-de-diputados-de-brasil/",
  "https://chile21.cl/entrevista-director-ejecutivo-de-chile-21-por-baleo-en-puerto-montt-queremos-un-presidente-que-no-solo-busque-frases-planfeteras/",
  "https://chile21.cl/directora-del-area-de-calidad-de-la-democracia-participa-en-debate-sobre-reformas-politicas-en-peru/",
  "https://chile21.cl/inscripciones-foro-globalizacion-impulso-tecnologico-nacional-y-modelo-de-desarrollo-la-izquierda-debate/",
  "https://chile21.cl/que-es-la-clase-media-directora-del-area-de-opinion-publica-y-comunicacion-politica-participa-en-panel-de-analisis-de-cnn-chile/",
  "https://chile21.cl/director-del-area-de-economia-participa-en-primer-encuentro-coyuntural-organizado-por-el-centro-de-productividad-aplicada-de-la-universidad-mayor/",
  "https://chile21.cl/directora-del-area-de-opinion-publica-y-comunicacion-politica-analiza-el-lanzamiento-del-libro-sinceramente-de-cristina-fernandez-y-el-escenario-politico-en-argentino-en-un-ano-electoral/",
  "https://chile21.cl/directora-area-calidad-de-la-democracia-defiende-adopcion-homoparental-y-analiza-controversias-en-sector-justicia/",
  "https://chile21.cl/marca-registrada-director-ejecutivo-de-chile-21-analiza-denuncias-de-irregularidades-en-la-pdi-y-los-desafios-de-las-policias-en-chile/",
  "https://chile21.cl/al-grano-enusc-2018-seguridad-y-desigualdad/",
  "https://chile21.cl/directora-del-area-del-area-de-opinion-publica-y-comunicacion-politica-analiza-procesos-politicos-elecciones-en-espana-y-el-recambio-de-liderazgos/",
  "https://chile21.cl/al-grano-respuestas-politicas-y-acciones-frente-al-cambio-climatico/",
  "https://chile21.cl/sumate-a-chile-21/",
  "https://chile21.cl/directora-del-area-de-calidad-de-la-democracia-analiza-proyecto-de-ley-sobre-eutanasia-en-radio-la-clave/",
  "https://chile21.cl/documento-gestion-de-personas-en-el-estado/",
  "https://chile21.cl/director-del-area-internacional-analiza-los-acontecimientos-del-peru-tras-el-suicidio-de-alan-garcia/",
  "https://chile21.cl/documento-ley-de-datos-personales/",
  "https://chile21.cl/presidenta-de-chile-21-analiza-actualidad-politica-de-la-semana-en-mesa-central-de-canal-13/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-analiza-plan-elige-vivir-sin-drogas-en-programa-sigamos-de-largo-de-canal-13/",
  "https://chile21.cl/directora-del-area-de-calidad-de-la-democracia-analiza-contingenia-en-radio-la-clave/",
  "https://chile21.cl/inscripciones-conferencia-lo-macro-y-lo-micro-en-el-desarrollo-economico-de-chile-firmas-instituciones-tecnologia-medioambiente-e-inclusion-social/",
  "https://chile21.cl/condolencias-por-lo-ocurrido-con-claudio-agurto/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-en-entrevista-con-adn-radio-las-campanas-del-gobierno-han-hecho-que-los-ninos-pierdan-confianza-en-los-adultos/",
  "https://chile21.cl/presidenta-de-chile-21-gloria-de-la-fuente-participa-como-expositora-en-el-secondo-forum-sul-futuro-della-democrazia-organizado-por-la-fondazione-giangiacomo-fertrinelli/",
  "https://chile21.cl/director-ejecutivo-de-chile-21-en-entrevista-con-cnn-chile-no-es-posible-que-nuestros-ninos-decidan-elegir-vivir-sin-drogas/",
  "https://chile21.cl/reserva-emociones-en-politica/",
  "https://chile21.cl/documento-ideas-y-datos-centrales-sobre-la-ley-de-isapres/",
  "https://chile21.cl/chile-21-invita-mesa-redonda-sobre-el-tpp-11-y-el-desarrollo-de-chile/",
  "https://chile21.cl/documento-reformas-al-control-preventivo-de-identidad/",
  "https://chile21.cl/director-del-area-de-ideas-politicas-conflicto-y-cambio-social-analiza-contingencia-por-prosur/",
  "https://chile21.cl/analisis-de-viviana-giacaman-en-programa-mentiras-verdaderas/",
  "https://chile21.cl/eduardo-vergara-por-control-de-identidad-a-menores-se-esta-disenando-una-politica-sin-sustento-alguno/",
  "https://chile21.cl/nuevo-director-ejecutivo-de-chile-21-debuta-con-creacion-de-equipo-de-seguridad-transversal-de-la-centroizquierda/",
  "https://chile21.cl/viviana-giacaman-en-radio-la-clave-4/",
  "https://chile21.cl/reserva-la-fecha-encuentro-generacion-bicentenario/",
  "https://chile21.cl/director-del-area-economica-de-chile-21-asiste-a-comision-de-trabajo-y-seguridad-social-de-la-camara-de-diputados/",
  "https://chile21.cl/beers-and-politics-las-mujeres-y-la-politica-una-conversacion-con-gloria-de-la-fuente/",
  "https://chile21.cl/inscripciones-taller-electoral-2019-fes-chile-21/",
  "https://chile21.cl/viviana-giacaman-en-radio-la-clave/",
  "https://chile21.cl/mesa-redonda-la-politica-exterior-chilena-una-politica-de-estado/",
  "https://chile21.cl/veronica-pinilla-participa-en-especial-8m-de-cnn-prime/",
  "https://chile21.cl/viviana-giacaman-en-mentiras-verdaderas-de-la-red/",
  "https://chile21.cl/gloria-de-la-fuente-en-seminario-empleo-publico-y-reforma-previsional-2/",
  "https://chile21.cl/cirugia-al-estado/",
  "https://chile21.cl/el-nuevo-trio-que-lidera-chile-21/",
  "https://chile21.cl/jaime-ensignia-las-relaciones-chile-bolivia-en-un-punto-cero/",
  "https://chile21.cl/simposio-la-agenda-2030-como-base-de-una-agenda-post-neoliberal/",
  "https://chile21.cl/360-de-cnn-chile-viviana-giacaman-conversando-sobre-las-salidas-politicas-al-conflicto-en-araucania/",
  "https://chile21.cl/la-directora-de-calidad-de-la-democracia-viviana-giacaman-conversando-sobre-las-salidas-politicas-al-conflicto-en-araucania-en-el-programa-360-de-cnn-chile/",
  "https://chile21.cl/gloria-de-la-fuente-en-t13-radio/",
  "https://chile21.cl/viviana-giacaman-en-combinacion-clave/",
  "https://chile21.cl/carlos-ominami-en-programa-que-pasa-si-olvido/",
  "https://chile21.cl/carlos-ominami-en-cnn-bolsonaro-la-ola-que-viene/",
  "https://chile21.cl/bet-gerber-en-diario-tv-universidad-de-chile-como-enfrentar-a-la-ultraderecha/",
  "https://chile21.cl/jaime-ensignia-en-el-periodista-tv-analisis-a-fondo-del-fallo-de-la-haya/",
  "https://chile21.cl/seminario-desafios-democraticos-a-30-anos-del-no/",
  "https://chile21.cl/bet-gerber-directora-de-opinion-publica-en-canal-24-horas/",
  "https://chile21.cl/carlos-ominami-se-reune-con-fernando-haddad/",
  "https://chile21.cl/carlos-ominami-en-brasil/",
  "https://chile21.cl/jaime-ensignia-en-radio-u-de-chile-2/",
  "https://chile21.cl/gloria-de-la-fuente-en-la-tercera-5/",
  "https://chile21.cl/seminario-la-guerra-comercial-y-sus-efectos-para-chile/",
  "https://chile21.cl/seminario-financiamiento-de-la-salud-en-chile/",
  "https://chile21.cl/seminario-educacion-y-democracia/",
  "https://chile21.cl/jaime-ensignia-en-politica-en-vivo-radio-u-chile/",
  "https://chile21.cl/gloria-de-la-fuente-en-t13-radio-2/",
  "https://chile21.cl/carlos-ominami-con-el-papa-en-santa-marta/",
  "https://chile21.cl/comunicado-de-prensa/",
  "https://chile21.cl/carlos-ominami-se-reune-con-papa-francisco/",
  "https://chile21.cl/simposio-agenda-2030/",
  "https://chile21.cl/la-relaciones-con-bolivia-y-la-politica-exterior/",
  "https://chile21.cl/sergio-bitar-en-emol-tv/"
)

library(rvest)
library(tidyverse)
library(openxlsx)

resultados <- list()

for (i in seq_along(enlaces)) {
  url <- enlaces[i]
  webpage <- read_html(url)
  
  fecha_publicacion <- webpage %>%
    html_nodes('meta[property="article:published_time"]') %>%
    html_attr("content")
  
  titulo <- webpage %>%
    html_nodes('meta[property="og:title"]') %>%
    html_attr("content")
  
  fecha_publicacion <- ifelse(length(fecha_publicacion) > 0, fecha_publicacion, NA)
  titulo <- ifelse(length(titulo) > 0, titulo, NA)
  
  data <- data.frame(Enlace = url,
                     Fecha_Publicacion = fecha_publicacion,
                     Titulo = titulo)
  
  resultados[[i]] <- data
  
  cat("Web scraping completado para el enlace", i, "\n")
}

resultados_completos <- bind_rows(resultados)

nombre_archivo <- "C21 Noticias.xlsx"
write.xlsx(resultados_completos, nombre_archivo, row.names = FALSE)

cat("Los datos se han guardado en el archivo", nombre_archivo, "\n")
